application:
  # Set if running behind Apache/Nginx + https
  protocol: "https://"
  layer: "production"
  fake_proxies_enabled: false

secret_token: some 128 char random hex string

logger:
  level: <%= ENV['LOGGER_LEVEL'] || WARN %>

edodb:
  adapter: jdbc
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@<yer_host>:<yer_port>:<yer_sid>
  username: <yer_username>
  password: <yer_password>
  pool: 95
  timeout: 5000

canvas_proxy:
  export_directory: '/home/app_calcentral/calcentral/tmp/canvas'
  # Set to "true" when Canvas allows it.
  delete_bad_emails: false

background_torquebox: true
background_threads:
  min: 10,
  max: 10,
  max_queue: 0  # unbounded work queue
